### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by ivanovd** [resoai/TileBoard#181]
Hi. I installed the tileboard as described, however, when I try to login from the browser I get ERR_CONNECTION_REFUSED in the browser and the following in the HASSIO log:

> Error doing job: SSL error errno:1 reason: HTTP_REQUEST
> Traceback (most recent call last):
>   File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
>   File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
>   File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
>   File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:841)

> Error doing job: SSL handshake failed
> Traceback (most recent call last):
>   File "uvloop/handles/stream.pyx", line 609, in uvloop.loop.UVStream._on_eof
>   File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
>   File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:841)

In my config I have changed ws:// to wss:// since I use SSL:

   serverUrl: "https://localhost:8123",
   wsUrl: "wss://localhost:8123/api/websocket",

I haven't changed anything else in the config.js since I wanted to only start and see what it is like.

**Comment by ivanovd** [comment]
Yeah, good catch. I left it as it was in the config.sample.js ... didn't even notice it was localhost.

I changed that to hassio.local and it worked :)

Thanks resoai
