### ISSUE TITLE
Issue with Network host options

### ISSUE THREAD

**Issue by piltous** [resoai/TileBoard#777]
Hello,
I was previously using an old version with HA and www folder for an IPAD3.
I tried to switch to the add-on app and it's works inside HA and with the API from my desktop and smartphone but not from the IPAD3 (error 401 Unauthorized).
I tried to enable a port (8999) in add-on conf so for me http://192.168.178.xx:8999/ but I have only a blue screen from any devices.
I'm not sure if it's an issue from the add-on or from my setup but I really would like to enjoy the last version on my old IPAD that I use for wall mount (I have small issue with TYPES.CAMERA and TYPES.MEDIA that seems to be fixed with the last release).
Thanks for your help!

**Comment by piltous** [comment]
Hello, many thanks for the release!
I'm certainly doing something wrong but I'm not able to reach the custome URL. I set 8999 in the conf and 
192.168.178.39:8999 
fall from everywhere on http://192.168.178.39:8999/null/auth/authorize?client_id=http%3A%2F%2F192.168.178.39%3A8999&redirect_uri=http%3A%2F%2F192.168.178.39%3A8999%2F%3Foauth%3D1 
with an 404 nginx error.
Not sure how to fix this...

**Comment by piltous** [comment]
So I added the long life token, now 192.168.178.39:8999 doesn't redirect to an "auth" url but still no luck to show something, still an emply blue page when it works fine with ingress.
any help is welcome.

**Comment by rchl** [comment]
Open developer tools in the browser and reload the page. Do you see any errors in the `Console` tab or any failing requests in the `Network` tab.

You could screenshot what you see if there is no private information in there.

**Comment by rchl** [comment]
Well, if you have problem with Ipad then I guess that could be difficult if not impossible to do...

There could be something in your config file that breaks in the old browser version. You could try playing with that or post it if you don't mind people seeing your entities.

**Comment by piltous** [comment]
Hi, thank you for your help. The issue is not only from the Ipad but also from my computer.
I don't have SSL enable in HA neither in Tileboard Add-on conf and this is maybe the source of the issue.
In the Console I have this websocket issue...

```
angular.js:15697 DOMException: Failed to construct 'WebSocket': The URL 'null/api/websocket' is invalid.
    at o._connect (http://192.168.178.39:8999/scripts/app-2dfad20a.js:50:17913)
    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:50:15397
    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:95657
    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:95795
    at c.$digest (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:101158)
    at c.$apply (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:103151)
    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:10446
    at Object.invoke (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:26451)
    at i (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:10367)
    at Object.Dt [as bootstrap] (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:10656) `Possibly unhandled rejection: {"stack":"Error: Failed to construct 'WebSocket': The URL 'null/api/websocket' is invalid.\n    at o._connect (http://192.168.178.39:8999/scripts/app-2dfad20a.js:50:17913)\n    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:50:15397\n    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:95657\n    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:95795\n    at c.$digest (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:101158)\n    at c.$apply (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:103151)\n    at http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:10446\n    at Object.invoke (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:26451)\n    at i (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:10367)\n    at Object.Dt [as bootstrap] (http://192.168.178.39:8999/scripts/app-2dfad20a.js:7:10656)"}`
(anonymous) @ angular.js:15697
(anonymous) @ angular.js:11956
c @ angular.js:18105
$digest @ angular.js:19241
$apply @ angular.js:19630
(anonymous) @ angular.js:1966
invoke @ angular.js:5208
i @ angular.js:1964
Dt @ angular.js:1984
(anonymous) @ init.js:15
n @ angular.js:3587
load (async)
Le @ angular.js:3600
fe @ angular.js:3325
fe @ angular.js:3319
window.initApp @ init.js:14
Z_ @ index.js:24
Q_.onload @ index.js:32
load (async)
(anonymous) @ index.js:32
(anonymous) @ index.js:34
192.168.178.39/:1 Error while trying to use the following icon from the Manifest: http://192.168.178.39:8999/favicon.png (Resource size is not correct - typo in the Manifest?)
```

**Comment by rchl** [comment]
What do you have set in the `General` HA settings:

<img width="673" alt="Screenshot 2021-11-04 at 20 13 47" src="https://user-images.githubusercontent.com/153197/140405033-995a9654-b578-42d8-84c8-f0f9a865f73e.png">

?

If nothing then you could try to set the Internal URL.

**Comment by piltous** [comment]
Right, it was not set and I disabled "useExternalUrl". It works now :)
Many thanks!!!
